# Set update schedule for GitHub Actions
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to requirements.txt
      interval: "daily"
