log_glob: log/counter_2018-03-*.log
processing_database: db/counter_db.sqlite3
path_types:
  investigations:
    - ^/api/datasets/[^\/]+$
    - ^/api/versions/\d+$
    - ^/stash/dataset/\S+$
    - ^/stash/data_paper/\S+$
  requests:
    - ^/api/datasets/[^\/]+/download$
    - ^/api/versions/\d+/download$
    - ^/api/downloads/\d+$
    - ^/stash/downloads/download_resource/\d+$
    - ^/stash/downloads/file_download/\d+$
    - ^/stash/downloads/file_stream/\d+$
    - ^/stash/downloads/async_request/\d+$
    - ^/stash/share/\S+$
robots_url: https://raw.githubusercontent.com/CDLUC3/Make-Data-Count/master/user-agents/lists/robot.txt
machines_url: https://raw.githubusercontent.com/CDLUC3/Make-Data-Count/master/user-agents/lists/machine.txt
#start_time: 2018-03-01 00:00:00
#end_time: 2018-04-01 00:00:00
start_date: 2018-03-01
end_date: 2018-03-31
# don't put filename extension, it will tack on the tsv or json in the code
output_file: tmp/test
platform: Dash
# only_calculate allows outputting stats from current database without having to crunch all the logs
# again and populate it (may be slow).
only_calculate: False
# specifying partial data will set the exception 3040: Partial Data Returned in the report because
# it's not a final report for the period.
partial_data: True
