log_glob: log/counter_2018-02-*.log
processing_database: db/counter_db.sqlite3
path_types:
  investigations:
    - ^/api/datasets/[^\/]+$
    - ^/api/versions/\d+$
    - ^/stash/dataset/\S+$
    - ^/stash/data_paper/\S+$
  requests:
    - ^/api/datasets/[^\/]+/download$
    - ^/api/versions/\d+/download$
    - ^/api/downloads/\d+$
    - ^/stash/downloads/download_resource/\d+$
    - ^/stash/downloads/file_download/\d+$
    - ^/stash/downloads/file_stream/\d+$
    - ^/stash/downloads/async_request/\d+$
    - ^/stash/share/\S+$
robots_url: https://raw.githubusercontent.com/CDLUC3/Make-Data-Count/master/user-agents/lists/robot.txt
machines_url: https://raw.githubusercontent.com/CDLUC3/Make-Data-Count/master/user-agents/lists/machine.txt
start_time: 2018-02-01 00:00:00
end_time: 2018-03-01 00:00:00
output_file: tmp/test.tsv
