log_files: log/counter_2018-02-13.log
processing_database: db/counter_db.sqlite3
path_types:
  investigations:
    - ^/api/datasets/[^\/]+$
    - ^/api/versions/\d+$
    - ^/stash/dataset/\S+$
    - ^/stash/data_paper/\S+$
  requests:
    - ^/api/datasets/[^\/]+/download$
    - ^/api/versions/\d+/download$
    - ^/api/downloads/\d+$
    - ^/stash/downloads/download_resource/\d+$
    - ^/stash/downloads/file_download/\d+$
    - ^/stash/downloads/file_stream/\d+$
    - ^/stash/downloads/async_request/\d+$
    - ^/stash/share/\S+$
robots_url: https://raw.githubusercontent.com/atmire/COUNTER-Robots/master/generated/COUNTER_Robots_list.txt
